### ISSUE TITLE
Windows database_migration datamodel_steps too small

### ISSUE THREAD

**Issue by Parilar** [prisma/lift#112]
Using a windows machine you will get an exception if your schema get's to big.
The problem is that text is to short at the columns **database_migration** and  **datamodel_steps**

Error: 

```
LiftEngine:stderr thread 'tokio-runtime-worker-1' panicked at 'called Result::unwrap() on an Err value: QueryError(MySqlError { ERROR 1406 (22001): Data too long for column 'datamodel_steps' at row 1 } +0ms
 LiftEngine:stderr stack backtrace: +1ms
```

My solution:
changed text to longtext

**Comment by divyenduz** [comment]
Related MySQL docs: 

- https://dev.mysql.com/doc/refman/8.0/en/column-count-limit.html
- https://dev.mysql.com/doc/refman/8.0/en/innodb-restrictions.html

For some reason, `text` type on this particular windows instance + MySQL installation had smaller size. This might be generic issue on MySQL+Windows but we are yet to validate that.

**Comment by divyenduz** [comment]
Note: the user had around ~70 models.

**Comment by divyenduz** [comment]
Note: Fixing this will be a breaking change whenever this is fixed.

**Comment by divyenduz** [comment]
@schickling will create a meta issue about Lift specs

**Comment by mavilein** [comment]
This is fixed now. I changed the column type for the MySQL connector for lift from `TEXT` to `LONGTEXT` which allows much longer strings. This fix will only be available to newly created projects. To fix an existing project i recommend the following procedure:
1. Delete the `_Migration` table in the database.
2. Delete the `prisma/migrations` folder in your project.
