### ISSUE TITLE
Remove database create logic inside lift, fail fast if the database doesn't exist.

### ISSUE THREAD

**Issue by matthewmueller** [prisma/lift#122]
Right now lift has all sorts of logic to create a database. This won't work for every datasource and it'd be better to create datasouces in `prisma init` or the `prisma studio` flows, where we can ask the user some questions and hold their hand.

If the user doesn't use the `prisma init` flow, we'll expect them to bring their own database (BYOD).

Instead Lift commands will check if it can connect to the database and fail fast if it can't connect. This will resolve #26 and it will make the migration engine code cleaner.

Thoughts @schickling ?

**Comment by pimeys** [comment]
My rust code is here:

https://github.com/prisma/prisma-engine/pull/34

Next week working with @timsuchanek to use this in lift/photon.

**Comment by timsuchanek** [comment]
Shipped in latest alpha.
