### ISSUE TITLE
?schema=public should be used by default, and some other issues

### ISSUE THREAD

**Issue by audacioustux** [prisma/lift#13]
* datasource url without schema param doesn't work, even if `schema =`  is set.
* public should be implicitly used if none is mentioned
* datasource doesn't work without `url`. even when host, port and other params are given
** is there any way to specify error log folder?

**Comment by mavilein** [comment]
Hey @audacioustux ,

thanks for reaching out! 🙏 URLs are the only connection mechanism that `lift` provides.
Your request for the default for the public schema has been implemented in the last preview release. Just run `npm install -g prisma2` to get it.
There is no way to specify an error log folder. Feel free to open a separate feature request with how you would like to specify it.
