### ISSUE TITLE
Tracking issue: breaking change in the database migration steps JSON in the last release

### ISSUE THREAD

**Issue by tomhoule** [prisma/lift#151]
The `steps` key was replaced by `original_steps` and `corrected_steps`, causing old migrations to fail to serialize, making lift unable to complete the migrations. This still needs to be confirmed, but truncating the `_Migrations` table should fix the issue.

This issue is for tracking the solution/possible hotfix.

@timsuchanek  @janpio  @mavilein

**Comment by mavilein** [comment]
Yes. Truncating the table will fix it.
We should be a little bit more precise when describing the issue:
> We changed the serialization format of the database migration of SQL migration connector. 

Without it is a bit unclear whether we could refer to the `steps.json` which is not the case here.

**Comment by divyenduz** [comment]
Internal note: @mavilein can this be closed?

**Comment by mavilein** [comment]
Yes.
