### ISSUE TITLE
README "Database Steps" and `steps.json` do not match when created via `prisma2 dev`

### ISSUE THREAD

**Issue by janpio** [prisma/lift#167]
1. Create a project
2. Run `prisma2 dev`
3. Change something in the `schema.prisma` to test out Dev Mode
4. Exit Dev Mode and run `prisma2 lift save`
5. Apply the migration to the DB with `prisma2 lift up`
6. Observe that the "Database Steps" are empty and `steps.json` has content:

![image](https://user-images.githubusercontent.com/183673/66501343-873db000-eac3-11e9-8fa8-4691e8ef35a6.png)

![image](https://user-images.githubusercontent.com/183673/66501371-96bcf900-eac3-11e9-95eb-e9a549894070.png)

As the database was created and filled via the dev/watch migrations during `prisma2 dev` this is of course correct, but super confusing and makes the `README.md` very environment dependent. The content created on the dev or staging system can be very different than what is actually executed in prod.

**Comment by tomhoule** [comment]
The fix PR (https://github.com/prisma/prisma-engine/pull/106) was just merged. It will be in the next preview (15).
