### ISSUE TITLE
support for char character

### ISSUE THREAD

**Issue by michaelchiche** [prisma/lift#17]
I have created my schema using the introspection, which worked great.
Then I did:
```sh
prisma dev
```

And i get an error on one Graphql String field
```sh
thread 'main' panicked at 'type char is not supported here yet. Column was: user_id'
```

So it looks like char is not managed yet with the migration using existing data?

**Comment by mavilein** [comment]
A fix will be available with the next Preview release on July 18th.

**Comment by janpio** [comment]
Could you please retest this @pantharshit00 and close if fixed? Thanks.

**Comment by pantharshit00** [comment]
This has been fixed now 🎉
