### ISSUE TITLE
 Error in lift engine for rpc getConfig

### ISSUE THREAD

**Issue by ansarizafar** [prisma/lift#19]
I am getting this error with postgres
![image](https://user-images.githubusercontent.com/5788284/60087348-48732c80-9756-11e9-9863-a845c67ee58b.png)

**Comment by Gbahaa** [comment]
libssl 1.1 is required for prisma2 and you need to install it for your Ubuntu. 

based on @dpetrick suggestion 
```
apt update && apt install libssl1.1
```
or you can download it from [Here](https://packages.ubuntu.com/bionic/amd64/libssl1.1/download
)

You can also report any missing library here 
https://github.com/prisma/prisma2-core/issues/2

**Comment by pantharshit00** [comment]
Closing in favour of prisma/prisma2#2
