### ISSUE TITLE
env() fallback

### ISSUE THREAD

**Issue by fiws** [prisma/lift#20]
It would be nice to use `env` with a fallback. 

For example `env("SQLITE_LOCATION", "dev.db")` or `env("SQLITE_LOCATION") || "dev.db"`

**Comment by matthewmueller** [comment]
@fiws thanks for bringing this up! It's currently in the spec, which means that we'll plan to implement it, but it's not available yet.

https://github.com/prisma/specs/tree/master/schema#env-function
