### ISSUE TITLE
Error in migration engine in case of connection to PostgreSQL on Google Cloud SQL

### ISSUE THREAD

**Issue by victordombrovskiy** [prisma/lift#207]
The following command:

```
 prisma2 lift save --name '' && prisma2 lift up
```

fails if I'm trying to connect to a PostgreSQL running on Google Cloud SQL. The next error is in logs:

```
ERROR  Oops, an unexpected error occured!
Error in migration engine: thread 'main' panicked at 'ConnectorError(QueryError(QueryError(ConnectionError(Error(None)
stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new_unresolved
   2: failure::backtrace::internal::InternalBacktrace::new
   3: <failure::backtrace::Backtrace as core::default::Default>::default
   4: <prisma_query::error::Error as core::convert::From<r2d2::Error>>::from
   5: sql_migration_connector::migration_database::PostgreSql::new
   6: sql_migration_connector::SqlMigrationConnector::postgres
   7: migration_engine::api::rpc::RpcApi::new
   8: migration_engine::api::rpc::RpcApi::new_async
   9: migration_engine::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
  12: __rust_maybe_catch_panic
  13: std::rt::lang_start_internal
  14: main
)
```

I use Prisma 2 preview version 0.14.2

Everything works properly if I use a local instance of PostgreSQL.

**Comment by pantharshit00** [comment]
I was unable to reproduce this with `prisma2@2.0.0-preview016.2, binary version: b72fd0a786adc77ba6c61d0a9637ff0371e433b0`.

I did run into https://github.com/prisma/prisma2/issues/884 while setting this up but after adding `&sslaccept=accept_invalid_certs` as a workaround to my connection string I was able to use that database. So please test this out again with preview 16.2 and with `&sslaccept=accept_invalid_certs` in the connection string.

**Comment by pantharshit00** [comment]
If you are still running into this, maybe tell me more about the configuration of your gcp instance. Also, maybe if you used the cli to create the instance share the gcloud cli command with me

**Comment by victordombrovskiy** [comment]
It was fixed in 16th release. Now I can connect to Google Cloud SQL.
