### ISSUE TITLE
Attribute @relation seems to ignore name with MySQL

### ISSUE THREAD

**Issue by tristancaron** [prisma/lift#21]
According to the documentation, the argument `name` of the attribute `@relation` determines the name of the table.

Using the connector MySQL, when table are created, they keep their default name (`_ManyToMany`) instead of the new name.

Example:
```
model Student {
  id          Int            @id
  school  School[]  @relation(id, name: "student_to_school")
}

model School {
  id            Int              @id
  student  Student[]  @relation(id, name: "student_to_school")
}

**Comment by mavilein** [comment]
Hey @tristancaron,

thanks for reaching out! 🙏 I could not reproduce this anymore with the latest version of lift. Can you please try again? If you are still running into this issue i am happy to reopen this.

**Comment by tristancaron** [comment]
Almost working, it's still adding an underscore to the front 
<img width="221" alt="image" src="https://user-images.githubusercontent.com/9624669/61237739-25aab700-a709-11e9-8f0c-e7a3a3393bdb.png">

**Comment by mavilein** [comment]
@tristancaron : We do this to ensure no name conflicts between relation tables and model tables. Does that cause problems for you?

**Comment by tristancaron** [comment]
Somehow I would to be able to enforce it like on prisma1. We have a strict name policy in my company, and tables will be already created by another system.

**Comment by mavilein** [comment]
@tristancaron : And that other system will also create the relation in a style matching Prisma? E.g. the relation columns have the correct names?

**Comment by tristancaron** [comment]
We will be close to this (from prisma1)
```
type User {
  id: ID! @id
  posts: [Post!]!
}

type Post {
  id: ID! @id
  user: User! @relation(link: TABLE, name: "MyRelation")
}

type MyRelation @relationTable {
  user: User!
  post: Post!
}
// This creates the following relation table 
CREATE TABLE "default$default"."MyRelation" (
    "post" varchar(25) NOT NULL,
    "user" varchar(25) NOT NULL
);
```

**Comment by mavilein** [comment]
Ok i see. In this case you will be required to add an extra model with that name.

**Comment by tristancaron** [comment]
Is it possible today with prisma2, if so, how should we proceed?

**Comment by mavilein** [comment]
Right now it's not possible since we require every model to have a singular id field right now. We want to start on removing this limitation next month. Feel free to reach out in public Slack to me if you have further questions!
