### ISSUE TITLE
String[] silently fails

### ISSUE THREAD

**Issue by matthewmueller** [prisma/lift#211]
In Postgres, `tags String[]` will act like it works, but it won't show up in the database.

```groovy
model Post {
  id        String   @default(cuid()) @id @unique
  tags      String[]
}
```

I believe the solution for postgres is to have `tags String[]` map to `tags text[] not null`

**Comment by matthewmueller** [comment]
Woahhh, nevermind. I just realized we implement this as a separate table. That's why it wasn't showing up.

**Comment by steebchen** [comment]
Wouldn't it make sense to allow mapping to `tags text[] not null`? I can imagine things getting slow with larger applications if there's a new table for _everything_.

**Comment by pantharshit00** [comment]
I know MySQL does not support array fields and postgres does so that might be the reason it is like that right now.
