### ISSUE TITLE
Named relation in schema breaks "lift up"

### ISSUE THREAD

**Issue by olup** [prisma/lift#213]
I have this schema 

```
generator photon {
  provider = "photonjs"
}

datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

model User {
  id     String  @default(cuid()) @id @unique
  email  String  @unique
  name   String?
  roles  Role[]
  drafts Page[]  @relation(name: "draftOwner")
}

model Role {
  slug      String  @default(cuid()) @id @unique
  users     User[]
  locked    Boolean @default(false)
  viewPages Page[]  @relation(name: "users_can_view_pages")
  editPages Page[]  @relation(name: "users_can_edit_pages")
}


model Page {
  id         String  @default(cuid()) @id @unique
  title      String
  slug       String  @unique
  content    String?
  published  Boolean
  draftOwner User?   @relation(name: "draftOwner")

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  canView Role[] @relation(name: "users_can_view_pages")
  canEdit Role[] @relation(name: "users_can_edit_pages")

  parents  Page[] @relation("Parents")
  children Page[] @relation("Parents")
}
```

I can save and up a first migration. However any following edits are throwing an error on `prisma2 lift up`. Specifically :

```
Response: {
  "jsonrpc": "2.0",
  "error": {
    "code": 4466,
    "message": "An error happened. Check the data field for details.",
    "data": {
      "type": "DataModelErrors",
      "code": 1001,
      "errors": [
        "Argument \"name\" is already specified.",
        "Argument \"name\" is already specified.",
        "Argument \"name\" is already specified.",
        "Argument \"name\" is already specified.",
        "Argument \"name\" is already specified.",
        "Argument \"name\" is already specified."
      ]
    }
  },
  "id": 2
}
An error happened. Check the data field for details.
```
I do not have the problem if I use the blog example's schema.

**Comment by olup** [comment]
I investigated a bit more. Adding elements to the schema bit by bit and migrating on and on I can say that the relation `@relation(name: "draftOwner")` is causing the problem (other reelations may too, but I did't check them). Meaning that I can migrate with this relation, then cannot `lift up` any subsequent changes in the schema.
Unamed relation doesn't seem to trigger this problem.

**Comment by olup** [comment]
After a bit more tests, the named relation `@relation("Parents")` in my Page model doesn't trigger any error. However, ` @relation(name: "users_can_view_pages")` breaks lift as well, so it seems that the problem originates in named relations linking two models, be it a `1:M` or `M:M` relation.

**Comment by pantharshit00** [comment]
I was successfully able to migrate the datamodel you have provided with `prisma2@2.0.0-preview016.2, binary version: b72fd0a786adc77ba6c61d0a9637ff0371e433b0`

![image](https://user-images.githubusercontent.com/22195362/69045768-8894bd80-0a1d-11ea-96f7-03d614b6bef5.png)


Can you please try again with the latest version and with a new database? There were a few breaking changes in lift in the past couple of weeks which might have affected your database.

**Comment by olup** [comment]
@pantharshit00 can you confirm you are able to migrate a change once this schema has been migrated in the first place ? I mean: migrate the schema , edit the schema (add whattever) migrate the change ( second migration) this is what breaks for me

**Comment by momakes** [comment]
This happens for me too.

**Comment by smartnet-club** [comment]
Para me tambien

**Comment by pantharshit00** [comment]
I can reproduce this now, thanks for detailed reproduction @smartnet-club

**Comment by pantharshit00** [comment]
I think it is a bug in our diffing logic cc @tomhoule

**Comment by tomhoule** [comment]
Can confirm it's probably that. I'll take this.

**Comment by smartnet-club** [comment]
The problem persists in 2.0.0-preview017.2
Second lift up on the same db scheme generates steps Create - Delete:

  "version": "0.3.14-fixed",
  "steps": [
    {
      "stepType": "CreateDirectiveArgument",
      "model": "Provider",
      "field": "id",
      "directive": "map",
      "argument": "name",
      "value": "\"ProviderId\""
    },
    {
      "stepType": "DeleteDirectiveArgument",
      "model": "Provider",
      "field": "id",
      "directive": "map",
      "argument": ""
    },
]

**Comment by greben99** [comment]
I can also confirm it is still an issue in 2.0.0-preview017.2.

**Comment by tomhoule** [comment]
I reproduced the issue in preview 16 and 17, and I can also confirm this is fixed in the latest alpha and in preview18 (that will be released today). The fix was in https://github.com/prisma/prisma-engine/pull/206

Please open a new issue if you still encounter problems using lift :)
