### ISSUE TITLE
Migrating an optional to a required self-relation where null-value already exist succeeds

### ISSUE THREAD

**Issue by nikolasburk** [prisma/lift#215]
I'm not sure if this is the expected behaviour, but I'd expect that Lift throws an error that tells me I can't make the relation required if there are existing null values already.

Here's my initial Prisma schema:

```prisma
generator photon {
  provider = "photonjs"
}

datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

model User {
  id        String  @default(cuid()) @id
  email     String  @unique
  name      String?
  reportsTo User?
}
```

This is the data in my DB:

![image](https://user-images.githubusercontent.com/4058327/68866115-38072280-06f4-11ea-92a9-e0bcc73275cb.png)

I am now migrating the `User` model as by making `reportsTo` required:

```prisma
model User {
  id        String  @default(cuid()) @id
  email     String  @unique
  name      String?
  reportsTo User
}
```

The migration works without issues. I now use the following Photon.js call:

```ts
const user = await photon.users.findOne({
  where: { email: "alice@prisma.io" },
  include: {
    reportsTo: true
  }
})
console.log(user!.reportsTo.name)
```

This doesn't give me a compiler error because from the outside it looks safe. But when I run it, Photon.js throws this error:

```
$ yarn dev
yarn run v1.19.1
$ ts-node ./script.ts
Error: 
Oops, an unknown error occured! This is on us, you did nothing wrong.
It occured in the `const user = await photon.users.findOne()` invocation in /Users/nikolasburk/Desktop/upgradetest/script.ts:19:35

  15 //     }
  16 //   }
  17 // })
  18 
→ 19   const user = await photon.users.findOne({

Reason: Application logic invariant error: received null value for field reportsTo which may not be null in query-engine/core/src/response_ir/internal.rs:228:26

Please create an issue in the photonjs repo with
your `schema.prisma` and the Photon method you tried to use 🙏:
https://github.com/prisma/photonjs/issues/new

    at PhotonFetcher.<anonymous> (/Users/nikolasburk/Desktop/upgradetest/node_modules/@generated/photon/index.js:54:27)
    at Generator.throw (<anonymous>)
    at rejected (/Users/nikolasburk/Desktop/upgradetest/node_modules/@generated/photon/index.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by pantharshit00** [comment]
I can also confirm this bug.
![image](https://user-images.githubusercontent.com/22195362/69059537-bc7edb80-0a3b-11ea-8e60-b065979017cb.png)

**Comment by tomhoule** [comment]
This should be fixed by https://github.com/prisma/prisma-engine/pull/134/files (merged recently). I'll try to take time to double check it doesn't happen anymore soon.

**Comment by janpio** [comment]
Can you confirm this is fixed in current alpha @pantharshit00?

**Comment by pantharshit00** [comment]
It throws nullconstraintvioliation now which I think is the right behaviour.
![image](https://user-images.githubusercontent.com/22195362/69742371-ae7b3a00-1162-11ea-95ea-6fd94f71e4a0.png)

We just need more beautiful errors now.

**Comment by janpio** [comment]
@niko can you confirm as well? Beautiful errors will come in next release - but if that is the correct one, I think we can already close this.

**Comment by nikolasburk** [comment]
Yup, I'mm seeing the same error 👍
