### ISSUE TITLE
Error running Lift on Windows

### ISSUE THREAD

**Issue by Kalcode** [prisma/lift#22]
On Windows 10 so it may be related to the enviroment.

Brand new clone, installed prisma2 via npm globally, followed the instructions

1. `npm install`
1. `npm install -g prisma2`
1. `prisma2 lift save --name 'init'`

And then i get the following error:

```shell
PS ~\Projects\photonjs\examples\typescript\graphql-apollo-server> prisma2 lift save --name 'init'
[migration-engine] error: Error: spawn C:\Users\kalan\AppData\Roaming\nvm\v12.4.0\node_modules\prisma2\migration-engine ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ' +
    'C:\\Users\\kalan\\AppData\\Roaming\\nvm\\v12.4.0\\node_modules\\prisma2\\migration-engine',
  path: 'C:\\Users\\kalan\\AppData\\Roaming\\nvm\\v12.4.0\\node_modules\\prisma2\\migration-engine',
  spawnargs: []
}
Error: Error in lift engine: ****
```

**Comment by mazzaker** [comment]
I use yarn instead of prisma2 cli directly and this works. So in wsl write yarn prisma2 save...
Did not tried with npm and powershell.

**Comment by janpio** [comment]
I can confirm this behavior on Windows (using both `cmd.exe` or Cmder):

```
E:\Projects\throwaway\prisma2_483_2  (script@1.0.0)
λ prisma2 lift save --name 'init'
[migration-engine] error: Error: spawn C:\Users\Jan\scoop\persist\nvm\nodejs\v12.6.0\node_modules\prisma2\migration-engine ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\Jan\\scoop\\persist\\nvm\\nodejs\\v12.6.0\\node_modules\\prisma2\\migration-engine',
  path: 'C:\\Users\\Jan\\scoop\\persist\\nvm\\nodejs\\v12.6.0\\node_modules\\prisma2\\migration-engine',
  spawnargs: [Array]
}
Error: spawn C:\Users\Jan\scoop\persist\nvm\nodejs\v12.6.0\node_modules\prisma2\migration-engine ENOENT
```

---

The file does exist not when you installed via `cmd.exe` (because of https://github.com/prisma/prisma2/issues/503):
![image](https://user-images.githubusercontent.com/183673/64388467-7e2e6e80-d03f-11e9-9065-d42e90f6cf45.png)

But it does _does_ exist when you installed Prisma2 using Cmder:

![image](https://user-images.githubusercontent.com/183673/64388424-56d7a180-d03f-11e9-917c-e1456e1ad4f4.png)

(The file is probably not executable on Windows as a child process it seems.)

**Comment by janpio** [comment]
The PR that was just merged and some other should make Prisma2 including Lift work much better on Windows (meaning not in WSL, but directly in `cmd.exe` or `Cmder`).
