### ISSUE TITLE
Migration Readme Incorrect

### ISSUE THREAD

**Issue by yovanoc** [prisma/lift#222]
Hello, I see that this is not yet updated. So how we can achieve hooks like this now?

![image](https://user-images.githubusercontent.com/7302317/69717240-f458e380-110b-11ea-89a1-c888e4c9cd82.png)

**Comment by divyenduz** [comment]
Internal note: candidate from bug triaging meeting

**Comment by timsuchanek** [comment]
Fixed in latest alpha.
You can try it out with `npm i -g prisma2@alpha`.
