### ISSUE TITLE
Lift is trying to recreate type aliases

### ISSUE THREAD

**Issue by pantharshit00** [prisma/lift#225]
Right now lift is trying to recreate type aliases that already exists.
![image](https://user-images.githubusercontent.com/22195362/69784432-c511a780-11db-11ea-9f1f-639703e16092.png)

In the above screenshot, type CUID already exists but lift is trying to recreate it and it is failing to do so.

To Reproduce:
1. Create a new Prisma 2 project using the CLI
2. Add a type alias, for example `type CUID = String @id @default(cuid())` and use it in one place
3. Migrate the database
4. Add another field of any type to any model.
5. Try to migrate the database again, you will see the error mentioned in the screenshot above.

Prisma2 version : `prisma2@2.0.0-preview017.1, binary version: 6159bf3a263921c3c28ee68e2c9e130b5a69c293`

**Comment by tomhoule** [comment]
I just reproduced this in the latest alpha. Will work on it now.
