### ISSUE TITLE
`lift save --create-db` create two db files

### ISSUE THREAD

**Issue by Weakky** [prisma/lift#229]
## Repro

```prisma
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

model User {
  id Int @id
}
```

Run

```
prisma2 lift save --name='init' --create-db
```

Result:
Two `dev.db` files created. One next to the `schema.prisma`, and one in the root of the project

```
prisma/
  schema.prisma
  dev.db
dev.db // not expected
```

Expected:
One `dev.db.` file created next to the `schema.prisma` file

```
prisma/
  schema.prisma
  dev.db
```

**Comment by pantharshit00** [comment]
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma2/issues/936
