### ISSUE TITLE
Prisma2 [ Did not find a relation for models ]

### ISSUE THREAD

**Issue by Gbahaa** [prisma/lift#24]
**Describe the bug**
It is not possible to add two relations in a model A to another same model B. 

**Reproduce**
1- prisma2 init
2- connect to MySql 5.7 database and use a new schema
3- set the following datamodel in project.prsima

```
model Place {
  id          Int       @id
  owner       User
}

model Space{
  id            Int       @id
  creator       User 
  members       User[] @relation(name: "SpaceMembers")
}

model User {
  id            Int       @id
  spaces        Space[] @relation(name: "SpaceMembers")
}
```

4- Then `prisma2 dev` raises the following error

```
Error: process exited with a non-zero code: 101
thread 'main' panicked at 'Did not find a relation for those for model User and field space', src/libcore/option.rs:1034:5
```

** Note **

- This error is cleared if we change the type of creator filed in the space model to be a string 

**Interesting behavior**
if we flip the order of space and user models in the datamodel, the error becomes 
```
Error: process exited with a non-zero code: 101
thread 'main' panicked at 'Did not find a relation for those for model Space and field members', src/libcore/option.rs:1034:5
```

**Expected behavior**
We can have as many relations as needed

**Versions (please complete the following information):**
 - Connector: MySQL
 - Prisma Server:  Prisma2 0.0.95
 - `prisma` CLI: Prisma2 0.0.95
 - OS:  `Ubuntu 16.04`

**Comment by tristancaron** [comment]
Same error

```
model User {
  managedCampaigns: Campaign[] @relation(name: "UserManager")
  followedCampaigns: Campaign[] @relation(name: "UserFollower")
}

model Campaign {
  managers: User[] @relation(name: "UserManager")
  followers: User[] @relation(name: "UserFollower")
}
```

**Comment by pantharshit00** [comment]
I can confirm this.

Interestingly enough if I manually perform a migration using `prisma2 lift save` and `prisma2 lift up` it creates the correct database schema.

![image](https://user-images.githubusercontent.com/22195362/61062433-db30ee00-a41b-11e9-895b-65d9f8b4611d.png)


`prisma2 dev` fails though:

![image](https://user-images.githubusercontent.com/22195362/61062461-e8e67380-a41b-11e9-93a5-39475838452d.png)

**Comment by timsuchanek** [comment]
Fixed in latest version.
