### ISSUE TITLE
--auto-approve is unknown when lifting down

### ISSUE THREAD

**Issue by Errorname** [prisma/lift#254]
I cannot use `--auto-approve` on `prisma2 lift down` while the help says I should be able to do it.

```
$ prisma2 lift down --auto-approve

! Unknown or unexpected option: --auto-approve

Migrate your database down to a specific state.

Usage

  prisma lift down [<dec|name|timestamp>]

Arguments

  [<dec>]   go down by an amount [default: 1]

Options

  --auto-approve   Skip interactive approval before migrating
  -h, --help       Displays this help message
  -p, --preview    Preview the migration changes
[... rest of help]
```

**Comment by Errorname** [comment]
The error comes from here: https://github.com/prisma/lift/blob/master/src/cli/commands/LiftDown.ts

Line 48, the argument "--auto-approve" is not listed, so it cannot be passed to the lift engine.

There is two solutions:
1. We shouldn't use "--auto-approve" on "lift down", so we must remove it from the help
2. We should make the command listen for the "--auto-approve" argument

Either way, I can make a PR if you can tell me which solution is preferred 🙂

**Comment by Errorname** [comment]
Looks like Lift.down() isn't using autoApprove at the moment https://github.com/prisma/lift/blob/master/src/Lift.ts

**Comment by timsuchanek** [comment]
Fixed by https://github.com/prisma/lift/pull/262
