### ISSUE TITLE
`prisma lift save` should not create a database - `prisma lift up` should

### ISSUE THREAD

**Issue by divyenduz** [prisma/lift#26]
Should `lift save` create the database or be stateless and let `lift up` do the mutative work? 

Currently, for SQLite, running `lift up` without a DB throws.

**Comment by schickling** [comment]
`prisma lift save` should **not** create (or write to) a database, `prisma lift up` should.

**Comment by matthewmueller** [comment]
Right now `lift save` creates a database, we need to adjust this.

**Comment by janpio** [comment]
Retro comment: New desire behavior, @matthewmueller will create the follow up issues.

**Comment by matthewmueller** [comment]
Closing in favor of: https://github.com/prisma/lift/issues/122
