### ISSUE TITLE
Stack trace flicker

### ISSUE THREAD

**Issue by matthewmueller** [prisma/lift#289]
I think this is probably ink + large stack trace, but it's hard to describe so I made a video:

https://www.dropbox.com/s/3nxhk18thstjvwn/flicker.mp4?dl=0

**Comment by divyenduz** [comment]
I am closing this one due to inactivity, if you still think that this is an issue, please comment here and tag me. Thank you 🙏

Also, we removed most of the related code, so, maybe this is already no longer relevant.
