### ISSUE TITLE
@unique does nothing

### ISSUE THREAD

**Issue by fiws** [prisma/lift#40]
I have a simple model with a unique field:

```prisma
model User {
    id               String            @default(cuid()) @id
    email            String            @unique
    password         String
}
```

The generated SQL for the migration looks like this:

```sql
CREATE TABLE "file:dev"."User"("id" TEXT NOT NULL  ,"email" TEXT NOT NULL DEFAULT '' ,"password" TEXT NOT NULL DEFAULT '' ,PRIMARY KEY ("id"));
```

the unique information is missing.

I am using `prisma2@0.0.99`

**Comment by pantharshit00** [comment]
This has been fixed.

![image](https://user-images.githubusercontent.com/22195362/61057908-d2d4b500-a413-11e9-9cd8-b1f0b8f22cd1.png)


I am using `0.0.128`
