### ISSUE TITLE
Ability to include/import models from additional files

### ISSUE THREAD

**Issue by michaelmitchell** [prisma/lift#41]
In v1 prisma.yml I could specify multiple files under datamodel to be included, sometimes I like to split my models up where it makes sense or include models from a different location.

It would be nice to have a way to import additional models into the project.prisma somehow, ultimately I can work around this by scripting something to run before generate, but I think this would be a valuable feature.

**Comment by pantharshit00** [comment]
Closing in favour of https://github.com/prisma/prisma2/issues/92
