### ISSUE TITLE
Regression: Required relations are not enforced as NOT NULL on the database level.

### ISSUE THREAD

**Issue by nikolasburk** [prisma/lift#98]
They are enforced by the query engine though. This is intermediate until we have fixed a limitation in the query engine.

**Comment by timsuchanek** [comment]
To add on this: We have checks on applications level, which are already working well and a non urgent issue for now.

**Comment by mavilein** [comment]
We can fix this once the redesign for the query engine core has been merged.

**Comment by dpetrick** [comment]
Migration engine now enforces not null on the DB level.
